/**
 * Data Models for Art Gallery - Inventory Management System
 *
 * Author: Haozhe Song
 * Student ID: 24832672
 * Course: PROG2005 Programming Mobile Systems
 */

/**
 * Category enumeration for inventory items
 */
export enum Category {
  Electronics = 'Electronics',
  Furniture = 'Furniture',
  Clothing = 'Clothing',
  Tools = 'Tools',
  Miscellaneous = 'Miscellaneous'
}

/**
 * Stock status enumeration (API uses lowercase 's')
 */
export enum StockStatus {
  InStock = 'In stock',
  LowStock = 'Low stock',
  OutOfStock = 'Out of stock'
}

/**
 * Inventory item interface matching backend database schema
 * API returns snake_case: item_id, item_name, etc.
 */
export interface InventoryItem {
  item_id: number;           // Unique, Auto-incrementing
  item_name: string;         // String, Required, Unique
  category: Category;        // Enum: Electronics, Furniture, Clothing, Tools, Miscellaneous
  quantity: number;          // Integer, Required
  price: number;            // Integer, Required
  supplier_name: string;    // String, Required
  stock_status: StockStatus; // Enum: In stock, Low stock, Out of stock
  featured_item: number;    // Integer, Default: 0
  special_note?: string;   // String, Optional
}

/**
 * DTO for creating a new inventory item
 * Note: item_id is auto-generated by backend
 */
export interface CreateInventoryItemDTO {
  item_name: string;
  category: Category;
  quantity: number;
  price: number;
  supplier_name: string;
  stock_status: StockStatus;
  featured_item?: number;
  special_note?: string;
}

/**
 * DTO for updating an existing inventory item
 */
export interface UpdateInventoryItemDTO {
  item_name?: string;
  category?: Category;
  quantity?: number;
  price?: number;
  supplier_name?: string;
  stock_status?: StockStatus;
  featured_item?: number;
  special_note?: string;
}

/**
 * Filter options for searching/filtering inventory
 */
export interface InventoryFilter {
  searchTerm?: string;
  category?: Category;
  stockStatus?: StockStatus;
  showFeaturedOnly?: boolean;
}

/**
 * Result type for operations that can fail
 */
export interface OperationResult<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

/**
 * API Error response
 */
export interface ApiError {
  error?: string;
  message?: string;
  [key: string]: unknown;
}

/**
 * Validation error interface
 */
export interface ValidationError {
  field: string;
  message: string;
}

/**
 * Sample data for demonstration (when API is unavailable)
 */
export const SAMPLE_INVENTORY_DATA: CreateInventoryItemDTO[] = [
  {
    item_name: 'iPhone 16 Mobile Phone',
    category: Category.Electronics,
    quantity: 168,
    price: 999,
    supplier_name: 'Apple',
    stock_status: StockStatus.InStock,
    featured_item: 1,
    special_note: 'New flagship model'
  },
  {
    item_name: 'Samsung Foldable Phone',
    category: Category.Electronics,
    quantity: 15,
    price: 1299,
    supplier_name: 'Samsung',
    stock_status: StockStatus.LowStock,
    featured_item: 1,
    special_note: 'Limited folding design'
  },
  {
    item_name: 'Huawei Tablet',
    category: Category.Electronics,
    quantity: 230,
    price: 499,
    supplier_name: 'Huawei',
    stock_status: StockStatus.InStock,
    featured_item: 0,
    special_note: 'Student office style'
  },
  {
    item_name: 'Sony Wireless Earbuds',
    category: Category.Electronics,
    quantity: 295,
    price: 199,
    supplier_name: 'Sony',
    stock_status: StockStatus.InStock,
    featured_item: 0,
    special_note: 'Active noise reduction'
  },
  {
    item_name: 'Xiaomi Smart Watch',
    category: Category.Electronics,
    quantity: 22,
    price: 159,
    supplier_name: 'Xiaomi',
    stock_status: StockStatus.LowStock,
    featured_item: 0,
    special_note: 'Health monitoring function'
  },
  {
    item_name: 'Seagate External Hard Drive',
    category: Category.Electronics,
    quantity: 0,
    price: 59,
    supplier_name: 'Seagate',
    stock_status: StockStatus.OutOfStock,
    featured_item: 0,
    special_note: 'Short-term out of stock'
  }
];

/**
 * Category options for dropdown
 */
export const CATEGORY_OPTIONS = Object.values(Category);

/**
 * Stock status options for dropdown
 */
export const STOCK_STATUS_OPTIONS = Object.values(StockStatus);
